from chalicelib.config import *

# environment vars
TOKEN_PATH = TDAMERITRADE_TOKEN_PATH
API_KEY = TDAMERITRADE_CLIENT_ID + '@AMER.OAUTHAP'
REDIRECT_URI = TDAMERITRADE_REDIRECT_URI
ACCOUNT_ID = TDAMERITRADE_ACCOUNT_ID
ALGOLIST_ID = TDAMERITRADE_ALGOLIST_ID
PASSPHRASE = CHALICE_PASSPHRASE

# options calculations
SHARES_PER_CONTRACT = 100
OPTIONS_CONTRACT_COMMISSION = .65
COMMISSION_PER_SHARE = OPTIONS_CONTRACT_COMMISSION / SHARES_PER_CONTRACT

# trade constants
STOP_LIMIT = 30
